// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChn1y20RypTe-wnFRSFRsWfQUTmUUmJo8',
    appId: '1:728979343966:web:777d676081f6ac72a9c2cf',
    messagingSenderId: '728979343966',
    projectId: 'taskflow-pro-001',
    authDomain: 'taskflow-pro-001.firebaseapp.com',
    storageBucket: 'taskflow-pro-001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbKZeiJ-_Q0tGg5ZAZeCYtMKvgvmG8Kv8',
    appId: '1:728979343966:android:ebb7dc813a813cd4a9c2cf',
    messagingSenderId: '728979343966',
    projectId: 'taskflow-pro-001',
    storageBucket: 'taskflow-pro-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAunkB4wljndVSzXRrOUrZfzgyGLT3k3o',
    appId: '1:728979343966:ios:db2c7433535a8958a9c2cf',
    messagingSenderId: '728979343966',
    projectId: 'taskflow-pro-001',
    storageBucket: 'taskflow-pro-001.firebasestorage.app',
    iosBundleId: 'com.example.taskflowPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAunkB4wljndVSzXRrOUrZfzgyGLT3k3o',
    appId: '1:728979343966:ios:db2c7433535a8958a9c2cf',
    messagingSenderId: '728979343966',
    projectId: 'taskflow-pro-001',
    storageBucket: 'taskflow-pro-001.firebasestorage.app',
    iosBundleId: 'com.example.taskflowPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChn1y20RypTe-wnFRSFRsWfQUTmUUmJo8',
    appId: '1:728979343966:web:984136413f4a09d1a9c2cf',
    messagingSenderId: '728979343966',
    projectId: 'taskflow-pro-001',
    authDomain: 'taskflow-pro-001.firebaseapp.com',
    storageBucket: 'taskflow-pro-001.firebasestorage.app',
  );
}
